name: colorful_baloons
description: "bloc, random, go_router, theme, freezed"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed: ^2.5.2
  go_router: ^13.2.4
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  bloc: ^8.0.0
  bloc_test: ^9.1.7 



flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: BebasNeue
      fonts: 
        - asset: assets/fonts/BebasNeue-Regular.ttf
        - weight: 500
    - family: Opinion
      fonts: 
        - asset: assets/fonts/OpinionProCondensed-SemiBold.otf
        - weight: 500

